language: objective-c
cache: cocoapods
podfile: Example/Podfile
osx_image: xcode8
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- npm install ios-sim -g
- ios-sim start --devicetypeid iPhone-6s
script:
# OCSlimProject Example Acceptance Tests (iOS, macOS)
- set -o pipefail && xcodebuild -workspace Example/OCSlimProject.xcworkspace -scheme OCSlimProject_AcceptanceUnitTestBundle_SimulatorWarmUpExcercise -destination 'platform=iOS Simulator,name=iPhone 6s' -destination-timeout 300 test
- set -o pipefail && xcodebuild -workspace Example/OCSlimProject.xcworkspace -scheme OCSlimProject_Example -destination 'platform=iOS Simulator,name=iPhone 6s' test
- set -o pipefail && xcodebuild -workspace Example/OCSlimProject.xcworkspace -scheme OCSlimProject_ExampleMac test
# OCSlimProjectTestBundleSupport Pod Unit Tests (iOS, macOS)
- set -o pipefail && xcodebuild -workspace Example/OCSlimProject.xcworkspace -scheme OCSlimProjectTestBundleSupportTests -destination 'platform=iOS Simulator,name=iPhone 6s' test
- set -o pipefail && xcodebuild -workspace Example/OCSlimProject.xcworkspace -scheme OCSlimProjectTestBundleSupportTestsMac test
# Pod Lib Lint (unavailable on xcode 8)
#- pod lib lint OCSlimProject.podspec --allow-warnings
#- pod lib lint OCSlimProjectTestBundleSupport.podspec --use-libraries --allow-warnings